/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_page;

import dashboard.admin_page;
import static dashboard.admin_page.pendaftaran;
import static dashboard.admin_page.data_petugas;
import static dashboard.admin_page.data_siswa;
import static dashboard.admin_page.edit;
import static dashboard.admin_page.edit_p;
import static dashboard.admin_page.hapus;
import static dashboard.admin_page.hapus_p;
import static dashboard.admin_page.hubungi;
import static dashboard.admin_page.print;
import static dashboard.admin_page.print_p;
import static dashboard.admin_page.psn_msk;
import static dashboard.admin_page.simpan;
import static dashboard.admin_page.simpan_p;
import static dashboard.admin_page.tampil;
import static dashboard.admin_page.tampil_p;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Randi
 */
public class login extends javax.swing.JFrame {
    admin_page a;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        a = new admin_page();
        
        a.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        mainPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel admin2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cbuser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon Login.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TK ERLANGGA");

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setText("Registrasi Accont Siswa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        jPanel5.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        mainPanel1.setLayout(new java.awt.CardLayout());

        admin2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/username.png"))); // NOI18N
        jLabel3.setText("Username");

        txtuser.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pass.png"))); // NOI18N
        jLabel4.setText("Password");

        txtpass.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Halaman Login");

        cbuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User", "Admin", "Petugas", "Siswa" }));

        javax.swing.GroupLayout admin2Layout = new javax.swing.GroupLayout(admin2);
        admin2.setLayout(admin2Layout);
        admin2Layout.setHorizontalGroup(
            admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(admin2Layout.createSequentialGroup()
                .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuser)
                            .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(cbuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(admin2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admin2Layout.setVerticalGroup(
            admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(cbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        mainPanel1.add(admin2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tka_erlangga", "root", "");
            Statement stat = koneksi.createStatement();
            ResultSet rs = stat.executeQuery("Select * from login_multiuser where username='"+txtuser.getText()+"'"
            + "and password='"+txtpass.getText()
            +"' and level='"+cbuser.getSelectedItem()+"'");
            
            rs.last();
            if(txtuser.getText().equals("username") && txtpass.getText().equals("password") && cbuser.getSelectedItem().equals("level")){
                a.setVisible(true);
                pendaftaran.setEnabled(true);
                data_siswa.setEnabled(true);
                data_petugas.setEnabled(true);
                hubungi.setEnabled(true);
                simpan.setEnabled(true);
                edit.setEnabled(true);
                tampil.setEnabled(true);
                hapus.setEnabled(true);
                simpan_p.setEnabled(true);
                edit_p.setEnabled(true);
                tampil_p.setEnabled(true);
                hapus_p.setEnabled(true);
                print.setEnabled(true);
                print_p.setEnabled(true);
                psn_msk.setEnabled(true);
                
                
                txtuser.setText("");
                txtpass.setText("");
                cbuser.setSelectedItem("Admin");
                this.dispose();
            } else if(rs.getRow()>=1){
                if(cbuser.getSelectedItem().equals("Admin")){
                    a.setVisible(true);
                    pendaftaran.setEnabled(true);
                    data_siswa.setEnabled(true);
                    data_petugas.setEnabled(true);
                    hubungi.setEnabled(true);
                    simpan.setEnabled(true);
                    edit.setEnabled(true);
                    tampil.setEnabled(true);
                    hapus.setEnabled(true);
                    simpan_p.setEnabled(true);
                    edit_p.setEnabled(true);
                    tampil_p.setEnabled(true);
                    hapus_p.setEnabled(true);
                    print.setEnabled(true);
                    print_p.setEnabled(true);
                    psn_msk.setEnabled(true);
                    
                    txtuser.setText("");
                    txtpass.setText("");
                    cbuser.setSelectedItem("Admin");
                    this.dispose();
                } else if(cbuser.getSelectedItem().equals("Petugas")){
                    a.setVisible(true);
                    pendaftaran.setEnabled(false);
                    data_siswa.setEnabled(true);
                    data_petugas.setEnabled(false);
                    hubungi.setEnabled(false);
                    simpan.setEnabled(true);
                    edit.setEnabled(true);
                    tampil.setEnabled(true);
                    hapus.setEnabled(true);
                    simpan_p.setEnabled(true);
                    edit_p.setEnabled(true);
                    tampil_p.setEnabled(true);
                    hapus_p.setEnabled(true);
                    print.setEnabled(false);
                    print_p.setEnabled(false);
                    psn_msk.setEnabled(true);

                    txtuser.setText("");
                    txtpass.setText("");
                    cbuser.setSelectedItem("Petugas");
                    this.dispose();
                } else if(cbuser.getSelectedItem().equals("Siswa")){
                    a.setVisible(true);
                    pendaftaran.setEnabled(true);
                    data_siswa.setEnabled(false);
                    data_petugas.setEnabled(false);
                    hubungi.setEnabled(true);
                    simpan.setEnabled(true);
                    edit.setEnabled(false);
                    tampil.setEnabled(true);
                    hapus.setEnabled(false);
                    simpan_p.setEnabled(true);
                    edit_p.setEnabled(false);
                    tampil_p.setEnabled(true);
                    hapus_p.setEnabled(false);
                    print.setEnabled(false);
                    print_p.setEnabled(false);
                    psn_msk.setEnabled(false);

                    txtuser.setText("");
                    txtpass.setText("");
                    cbuser.setSelectedItem("Siswa");
                    this.dispose();
                } else if(rs.getRow()==0){
                    JOptionPane.showMessageDialog(null, "Maaf login gagal, Perikas Kembali Username Dan Password ");
                    a.setVisible(false);
                    data_siswa.setEnabled(false);
                    data_petugas.setEnabled(false);
                }
                stat.close();
            }
        } catch (SQLException e) {
            System.out.print("Eror"+e);
        }

//        con = koneksi.getConnection();
//        String sql = "SELECT * FROM tb_admin WHERE username=? and password=?";
//        try{
//            pst=(PreparedStatement)con.prepareStatement(sql);
//            pst.setString(1, user.getText());
//            pst.setString(2, pass.getText());
//            rs=pst.executeQuery();
//            String username = user.getText();
//            String password = pass.getPassword().toString();
//            if(username.isEmpty() || password.isEmpty()){
//                JOptionPane.showMessageDialog(this, "Username and Password should not be empety", "Error", JOptionPane.ERROR_MESSAGE);
//            }else if(rs.next()){
//                JOptionPane.showMessageDialog(null, "Anda Berhasil Login");
//                admin_page start=new admin_page();
//                start.setVisible(true);
//                this.dispose();
//            }else{
//                JOptionPane.showMessageDialog(null, "Username atau Password Salah", "Pesan", JOptionPane.ERROR_MESSAGE);
//            }
//
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        registrasi start = new registrasi();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
